### ISSUE TITLE
There is an issue with the 'give money' code in the ESX portion.

### ISSUE THREAD

**Issue by CaptainAvenger** [IceSystem/ice_trophies#1]
https://github.com/IceClusters/ictrophies/blob/6447dc50a9c7d2f10dc7fb91bd71535a630a21be/src/server/main.lua#L75
about the ESX part, It's not 'player.setAccountMoney' but 'player.addAccountMoney' is the correct way. Otherwise, the player's money is set directly to that amount.

**Comment by deiividdz** [comment]
thank you for reporting it, we have just uploaded a new update ❤️
